// This file is generated by PAC. Do not edit manually.
import type { Events } from "@polar-sh/sdk/models/components/eventsingest.js";

type DefinedRecord<T extends object> = Partial<{ [Key in keyof T]: Exclude<T[Key], undefined> }>;
const omitUndefined = <T extends object>(value: T): DefinedRecord<T> =>
  Object.fromEntries(
    Object.entries(value).filter(([, entry]) => entry !== undefined),
  ) as DefinedRecord<T>;

export const products = {
  pro: {
    id: "28d02d6d-350d-4c27-815c-44b121eba231",
    name: "Pac Pro plan",
    description: "For serious users",
    visibility: "public",
    recurringInterval: "month",
    recurringIntervalCount: 3,
    isArchived: false,
    metadata: {},
    prices: [
      {
        id: "f58314dd-b8f5-4149-9c5d-f1d842bb2566",
        amountType: "fixed",
        priceAmount: "40",
        priceCurrency: "usd",
        isArchived: false,
      },
      {
        id: "ca59653a-e6c2-4f59-9730-930e682cf735",
        amountType: "metered_unit",
        priceCurrency: "usd",
        isArchived: false,
        unitAmount: "0.001",
        capAmount: "100",
        meterId: "d7cf5a32-97c3-48b3-b7d2-bce7ff04134a",
      },
    ],
    benefits: [
      {
        id: "7ed94f68-fe97-4d4f-b108-a526efe1c05f",
      },
      {
        id: "46b86b12-fb81-446f-bbf7-dd3498d3e452",
      },
    ],
  },
} as const;

export const meters = {
  tokens: {
    id: "d7cf5a32-97c3-48b3-b7d2-bce7ff04134a",
    name: "Pac tokens",
    unit: "token",
    customLabel: null,
    customMultiplier: null,
    filter: {
      conjunction: "and",
      clauses: [
        {
          property: "name",
          operator: "eq",
          value: "token_consumed",
        },
      ],
    },
    aggregation: {
      func: "sum",
      property: "total_tokens",
    },
    metadata: {},
    archivedAt: null,
  },
} as const;

export const benefits = {
  "included-tokens": {
    id: "46b86b12-fb81-446f-bbf7-dd3498d3e452",
    type: "meter_credit",
    description: "Included monthly tokens",
    isDeleted: false,
    metadata: {},
    properties: {
      units: 10000,
      rollover: false,
      meterId: "d7cf5a32-97c3-48b3-b7d2-bce7ff04134a",
    },
  },
  "custom-note": {
    id: "7ed94f68-fe97-4d4f-b108-a526efe1c05f",
    type: "custom",
    description: "Invite link",
    isDeleted: false,
    metadata: {},
    properties: {
      note: "Visit this link",
    },
  },
} as const;

export type TokenConsumedEventMetadata = {
  total_tokens: number;
  model: string;
  cache_hit?: boolean | undefined;
};

export type TokenConsumedEventInput = {
  timestamp?: Date | undefined;
  organizationId?: string | null | undefined;
  externalId?: string | null | undefined;
  parentId?: string | null | undefined;
  metadata: TokenConsumedEventMetadata;
} & (
  | {
      customerId: string;
      memberId?: string | null | undefined;
      externalCustomerId?: never;
      externalMemberId?: never;
    }
  | {
      externalCustomerId: string;
      externalMemberId?: string | null | undefined;
      customerId?: never;
      memberId?: never;
    }
);

const toPolarTokenConsumedEvent = (input: TokenConsumedEventInput): Events => {
  const { timestamp, organizationId, externalId, parentId } = input;
  const metadata = omitUndefined(input.metadata);

  if (input.customerId !== undefined) {
    return {
      timestamp,
      organizationId,
      externalId,
      parentId,
      customerId: input.customerId,
      memberId: input.memberId,
      name: "token_consumed",
      metadata,
    };
  }

  return {
    timestamp,
    organizationId,
    externalId,
    parentId,
    externalCustomerId: input.externalCustomerId,
    externalMemberId: input.externalMemberId,
    name: "token_consumed",
    metadata,
  };
};

export class TokenConsumedEvent {
  declare readonly timestamp: Date | undefined;
  declare readonly name: string;
  declare readonly organizationId: string | null | undefined;
  declare readonly externalId: string | null | undefined;
  declare readonly parentId: string | null | undefined;
  declare readonly metadata: DefinedRecord<TokenConsumedEventMetadata>;
  declare readonly customerId: string;
  declare readonly memberId: string | null | undefined;
  declare readonly externalCustomerId: string;
  declare readonly externalMemberId: string | null | undefined;

  constructor(input: TokenConsumedEventInput) {
    Object.assign(this, toPolarTokenConsumedEvent(input));
  }
}
