packages:
  - .
  - "!alchemy-effect/**"
  - "!sst/**"

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - msgpackr-extract
  - protobufjs

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
