export type { ResourceAddress } from "./core/address.js";
export type { ResourceKind } from "./core/kind.js";
export type {
  CurrentResource,
  DesiredResource,
  ResourceEnvelope,
  ResourceSource,
} from "./core/resource.js";

export { Benefit, benefitSpec } from "./resources/benefit.js";
export type {
  BenefitAddress,
  BenefitConfig,
  BenefitFeatureFlagSpec,
  BenefitKind,
  BenefitMetadata,
  BenefitMetadataValue,
  BenefitMeterCreditSpec,
  BenefitResource,
  BenefitSpec,
  CurrentBenefitResource,
  FeatureFlagBenefitConfig,
  MeterCreditBenefitConfig,
  MeterReference,
} from "./resources/benefit.js";
export {
  Meter,
  aggregate,
  and,
  avg,
  count,
  eventName,
  eventTimestamp,
  max,
  metadata,
  min,
  or,
  sum,
  unique,
  where,
} from "./resources/meter.js";
export type {
  AggregationFunction,
  CountAggregation,
  CountAggregationFunction,
  CurrentMeterResource,
  MeterAddress,
  MeterAggregation,
  MeterAggregationSpec,
  MeterConfig,
  MeterFilter,
  MeterFilterClause,
  MeterFilterClauseSpec,
  MeterFilterConjunction,
  MeterFilterOperator,
  MeterFilterSpec,
  MeterFilterValue,
  MeterKind,
  MeterResource,
  MeterSpec,
  MeterTimestampFilterValue,
  PropertyAggregation,
  PropertyAggregationFunction,
  UniqueAggregation,
  UniqueAggregationFunction,
} from "./resources/meter.js";
export {
  Product,
  customPrice,
  fixedPrice,
  freePrice,
  meteredUnitPrice,
} from "./resources/product.js";
export type {
  CurrentProductResource,
  CustomPriceConfig,
  FixedPriceConfig,
  FreePriceConfig,
  MeteredUnitPriceConfig,
  ProductAddress,
  ProductConfig,
  ProductCustomPriceSpec,
  ProductFixedPriceSpec,
  ProductFreePriceSpec,
  ProductKind,
  ProductMeteredUnitPriceSpec,
  ProductPriceConfig,
  ProductPriceSpec,
  ProductResource,
  ProductSpec,
} from "./resources/product.js";
